<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="HidSharp">
      <HintPath>libs\HidSharp.dll</HintPath>
    </Reference>
    <Reference Include="OpenTabletDriver.Plugin">
      <HintPath>libs\OpenTabletDriver.Plugin.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="VMultiLib\**\*.cs" />
  </ItemGroup>
</Project>
