<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>ClipStudioBridge.VMultiOtd</AssemblyName>
    <RootNamespace>ClipStudioBridge.VMultiOtd</RootNamespace>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="OpenTabletDriver.Plugin">
      <HintPath>..\..\_refs\OpenTabletDriver.Plugin.dll</HintPath>
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </Reference>
  </ItemGroup>

</Project>
